class_name PowerUpsConstants
extends Node

# Power-Ups duration
const SPEED_BOOST_SELF_DURATION := 3.0
const SPEED_BOOST_OTHER_DURATION := 3.0
const SPEED_REDUCE_SELF_DURATION := 10.0
const SPEED_REDUCE_OTHER_DURATION := 5.0
const INVERTER_OTHER_DURATION := 5.0
const DROP_DURATION := 5.0
const UNTRAIL_SELF_DURATION := 5.0
const FAT_OTHER_DURATION := 7.5
const THIN_SELF_DURATION := 15.0
const SQUARE_SELF_DURATION := 15.0
const SQUARE_OTHER_DURATION := 7.5
const CLEAR_DURATION := 0.0
const PASS_BORDERS_SELF_DURATION := 15.0
const PASS_BORDERS_OTHER_DURATION := 10.0
const SURPRISE_DURATION := 0.0
const FREEZE_OTHER_DURATION := 3.0

# Power-Ups spawn chance
const ORIGINAL_FRAMERATE := 30.0
const SPEED_BOOST_SELF_CHANCE := 70.0
const SPEED_BOOST_OTHER_CHANCE := 70.0
const SPEED_REDUCE_SELF_CHANCE := 70.0
const SPEED_REDUCE_OTHER_CHANCE := 70.0
const INVERTER_OTHER_CHANCE := 80.0
const DROP_CHANCE := 80.0
const UNTRAIL_SELF_CHANCE := 70.0
const FAT_OTHER_CHANCE := 50.0
const THIN_SELF_CHANCE := 70.0
const SQUARE_SELF_CHANCE := 70.0
const SQUARE_OTHER_CHANCE := 70.0
const CLEAR_CHANCE := 80.0
const PASS_BORDERS_SELF_CHANCE := 70.0
const PASS_BORDERS_OTHER_CHANCE := 70.0
const SURPRISE_CHANCE := 80.0
const FREEZE_OTHER_CHANCE := 70.0

# Power-Ups coefficients
const SPEED_BOOST_SELF_SPEEDCOEF := 2.0
const SPEED_BOOST_SELF_RADIUSCOEF := 1.5
const SPEED_BOOST_OTHER_SPEEDCOEF := 2.0
const SPEED_BOOST_OTHER_RADIUSCOEF := 1.5
const SPEED_REDUCE_SELF_SPEEDCOEF := 0.5
const SPEED_REDUCE_SELF_RADIUSCOEF := 1/1.5
const SPEED_REDUCE_OTHER_SPEEDCOEF := 0.5
const SPEED_REDUCE_OTHER_RADIUSCOEF := 1/1.5
const FAT_OTHER_SIZECOEF := 2.0
const THIN_SELF_SIZECOEF := 0.5
const POWERUP_FACTOR_DROP_BOOST := 4.0
