class_name PowerUpsConstants
extends Node

# Power-Ups duration
const SPEED_BOOST_SELF_DURATION := 3.0
const SPEED_BOOST_OTHER_DURATION := 3.0
const SPEED_REDUCE_SELF_DURATION := 10.0
const SPEED_REDUCE_OTHER_DURATION := 5.0
const INVERTER_OTHER_DURATION := 5.0
const DROP_DURATION := 5.0
const UNTRAIL_SELF_DURATION := 5.0
const FAT_OTHER_DURATION := 7.5
const THIN_SELF_DURATION := 15.0
const SQUARE_SELF_DURATION := 15.0
const SQUARE_OTHER_DURATION := 7.5
const CLEAR_DURATION := 0.0
const PASS_BORDERS_SELF_DURATION := 15.0
const PASS_BORDERS_OTHER_DURATION := 10.0
const SURPRISE_DURATION := 0.0
const FREEZE_OTHER_DURATION := 3.0

# Power-Ups spawn chance
const SPEED_BOOST_SELF_CHANCE := 70
const SPEED_BOOST_OTHER_CHANCE := 70
const SPEED_REDUCE_SELF_CHANCE := 70
const SPEED_REDUCE_OTHER_CHANCE := 70
const INVERTER_OTHER_CHANCE := 80
const DROP_CHANCE := 80
const UNTRAIL_SELF_CHANCE := 70
const FAT_OTHER_CHANCE := 50
const THIN_SELF_CHANCE := 70
const SQUARE_SELF_CHANCE := 70
const SQUARE_OTHER_CHANCE := 70
const CLEAR_CHANCE := 80
const PASS_BORDERS_SELF_CHANCE := 70
const PASS_BORDERS_OTHER_CHANCE := 70
const SURPRISE_CHANCE := 80

# Power-Ups coefficients
const SPEED_BOOST_SELF_SPEEDCOEF := 2.0
const SPEED_BOOST_SELF_ROTSPEEDCOEF := 1/1.5
const SPEED_BOOST_OTHER_SPEEDCOEF := 2.0
const SPEED_BOOST_OTHER_ROTSPEEDCOEF := 1/1.5
const SPEED_REDUCE_SELF_SPEEDCOEF := 1/2
const SPEED_REDUCE_SELF_ROTSPEEDCOEF := 1.5
const SPEED_REDUCE_OTHER_SPEEDCOEF := 1/2
const SPEED_REDUCE_OTHER_ROTSPEEDCOEF := 1.5
const FAT_OTHER_SIZECOEF := 2.0
const THIN_SELF_SIZECOEF := 0.5